"""CashPilot-gan: two hand-maintained lists both drifted from the catalog.

Filed as "the docs site nav is a mess", but the diagnosis is narrower and the
evidence is exact. One service was added and two lists were not updated:

* ``mkdocs.yml`` listed **51 of 52** guides, so ``proxybase-xyz.md`` was
  reachable only by URL — orphaned from the site's own navigation;
* ``docs/guides/README.md`` linked **49** services and announced "**49
  services**" while the catalog held **50** — missing the same one.

Both are now generated from ``services/*/*.yml`` by
``scripts/sync_docs_nav.py``, and the tests below fail when they drift again.
That matters more than the one-off fix: the catalog gains services regularly,
and a list nobody regenerates is the defect, not the symptom.

Also, the flat alphabetical list is grouped by the catalog's own four
categories. A visitor asking "what can I run on a box with no GPU and a fast
connection" could previously only scan 52 siblings.
"""

from __future__ import annotations

import collections
import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
MKDOCS = ROOT / "mkdocs.yml"
INDEX = ROOT / "docs" / "guides" / "README.md"
GUIDES = ROOT / "docs" / "guides"
SCRIPT = ROOT / "scripts" / "sync_docs_nav.py"

#: Files under docs/guides/ that are not service guides.
NON_SERVICE = {"README", "prometheus-metrics"}


def catalog_slugs() -> set[str]:
    slugs = set()
    for path in (ROOT / "services").glob("*/*.yml"):
        if path.name.startswith("_"):
            continue
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        slugs.add(data.get("slug") or path.stem)
    return slugs


def nav_refs() -> list[str]:
    text = MKDOCS.read_text(encoding="utf-8")
    return re.findall(r"guides/([\w.-]+)\.md", text[text.index("\nnav:") :])


class TestNoGuideIsOrphaned:
    """The concrete defect: a guide on disk that the nav never links."""

    def test_the_catalog_is_not_empty(self):
        """Otherwise every assertion below is vacuously true."""
        assert len(catalog_slugs()) >= 21

    def test_every_service_guide_is_in_the_nav(self):
        missing = sorted({p.stem for p in GUIDES.glob("*.md")} - NON_SERVICE - set(nav_refs()))
        assert not missing, f"reachable only by URL: {missing}"

    def test_every_catalog_service_has_a_guide_in_the_nav(self):
        missing = sorted(catalog_slugs() - set(nav_refs()))
        assert not missing, f"catalog services with no navigable guide: {missing}"

    def test_the_nav_has_no_dangling_entries(self):
        on_disk = {p.stem for p in GUIDES.glob("*.md")}
        assert not sorted(set(nav_refs()) - on_disk)

    def test_no_page_appears_in_the_nav_twice(self):
        """The first generated run listed prometheus-metrics in two places.

        It already had a top-level entry, and the generator added it to the
        Service Guides section as well. Caught by COUNTING refs, not by reading
        the output — 53 refs for 52 files.
        """
        dupes = [ref for ref, n in collections.Counter(nav_refs()).items() if n > 1]
        assert not dupes, f"listed twice in the nav: {dupes}"


class TestTheIndexMatchesTheCatalog:
    def test_every_service_is_linked_from_the_index(self):
        linked = set(re.findall(r"\]\(([\w.-]+)\.md\)", INDEX.read_text(encoding="utf-8")))
        missing = sorted(catalog_slugs() - linked)
        assert not missing, f"absent from the guides index: {missing}"

    def test_the_advertised_count_is_the_real_count(self):
        """The index said "49 services" while the catalog held a different count."""
        stated = re.search(r"\*\*(\d+) providers\*\*", INDEX.read_text(encoding="utf-8"))
        assert stated, "the index no longer states how many providers there are"
        assert int(stated.group(1)) == len(catalog_slugs())

    def test_it_is_marked_generated(self):
        """A hand edit would be silently overwritten; say so at the top."""
        assert "GENERATED by scripts/sync_docs_nav.py" in INDEX.read_text(encoding="utf-8")[:200]


class TestGuidesAreGroupedByCategory:
    def test_the_nav_uses_the_catalog_categories(self):
        text = MKDOCS.read_text(encoding="utf-8")
        block = text[text.index("  - Service Guides:") :]
        for heading in ("Bandwidth Sharing", "DePIN"):
            assert f"- {heading}:" in block, f"nav is not grouped by {heading}"

    def test_the_guides_are_not_one_flat_list(self):
        """The original shape: 52 alphabetical siblings under one heading."""
        text = MKDOCS.read_text(encoding="utf-8")
        block = text[text.index("  - Service Guides:") :]
        block = block[: block.index("\n  - ", 1)] if "\n  - " in block[1:] else block
        # Guides sit one level deeper than the category headings that hold them.
        assert re.search(r"^      - .+: guides/", block, re.M), "no guide is nested under a category"


class TestTheGeneratorIsTheSourceOfTruth:
    def test_the_script_exists_and_runs(self):
        result = subprocess.run(
            [sys.executable, str(SCRIPT), "--check"], cwd=ROOT, capture_output=True, text=True, check=False
        )
        assert result.returncode == 0, result.stdout + result.stderr

    def test_check_mode_detects_drift(self):
        """A --check that cannot fail is decorative.

        Adds a service to the catalog in a temp copy of the tree and asserts the
        checker notices, rather than trusting that it would.
        """
        import shutil
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            dst = Path(tmp) / "repo"
            shutil.copytree(
                ROOT,
                dst,
                ignore=shutil.ignore_patterns(
                    ".git", ".venv", "node_modules", "site", "__pycache__", ".beads", "htmlcov"
                ),
            )
            (dst / "services" / "bandwidth" / "zzdrift.yml").write_text(
                "slug: zzdrift\nname: ZZ Drift\ncategory: bandwidth\nstatus: active\n", encoding="utf-8"
            )
            (dst / "docs" / "guides" / "zzdrift.md").write_text("# ZZ Drift\n", encoding="utf-8")
            result = subprocess.run(
                [sys.executable, str(dst / "scripts" / "sync_docs_nav.py"), "--check"],
                cwd=dst,
                capture_output=True,
                text=True,
                check=False,
            )
            assert result.returncode != 0, "a new service did not register as drift"
            assert "Out of date" in result.stdout

    def test_it_refuses_a_guide_with_no_catalog_entry(self):
        """Silently dropping it from the nav is how the orphan happened."""
        text = SCRIPT.read_text(encoding="utf-8")
        assert "guides with no catalog entry" in text

    def test_it_will_not_write_an_empty_nav(self):
        """A catalog that fails to load must not erase 52 entries."""
        assert "refusing to write an empty nav" in SCRIPT.read_text(encoding="utf-8")


class TestGuideContentIsUntouched:
    """The bead is explicit: do not rewrite guide content, and referral links
    live in these files. Referral URLs are revenue."""

    @pytest.mark.parametrize("slug", ["iproyal", "traffmonetizer"])
    def test_referral_links_survive(self, slug):
        text = (GUIDES / f"{slug}.md").read_text(encoding="utf-8")
        assert re.search(r"https?://", text), f"{slug}.md lost every link"

    def test_the_generator_only_writes_the_index_and_the_nav(self):
        """Structural: it must not open any other guide for writing."""
        text = SCRIPT.read_text(encoding="utf-8")
        writes = re.findall(r"(\w+)\.write_text\(", text)
        assert set(writes) <= {"INDEX", "MKDOCS"}, f"the generator writes to {set(writes)}"
