"""Tests for compose file generation."""

import os
from unittest.mock import patch

os.environ.setdefault("CASHPILOT_API_KEY", "test-fleet-key")

import pytest
import yaml

from app import compose_generator


def _mock_service(
    slug="honeygain",
    name="Honeygain",
    image="honeygain/honeygain:latest",
    env=None,
    ports=None,
    volumes=None,
    category="bandwidth",
    network_mode=None,
    cap_add=None,
    command=None,
):
    svc = {
        "name": name,
        "slug": slug,
        "category": category,
        "status": "active",
        "description": "Test service",
        "docker": {
            "image": image,
            "env": env or [],
            "ports": ports or [],
            "volumes": volumes or [],
        },
    }
    if network_mode:
        svc["docker"]["network_mode"] = network_mode
    if cap_add:
        svc["docker"]["cap_add"] = cap_add
    if command:
        svc["docker"]["command"] = command
    return svc


class TestServiceToCompose:
    def test_basic_service(self):
        svc = _mock_service()
        result = compose_generator._service_to_compose(svc)
        assert result is not None
        assert result["image"] == "honeygain/honeygain:latest"
        assert result["container_name"] == "cashpilot-honeygain"
        assert result["restart"] == "always"

    def test_no_image_returns_none(self):
        svc = _mock_service(image="")
        svc["docker"]["image"] = ""
        result = compose_generator._service_to_compose(svc)
        assert result is None

    def test_no_docker_returns_none(self):
        svc = {"name": "No Docker", "slug": "nodock", "docker": {}}
        result = compose_generator._service_to_compose(svc)
        assert result is None

    def test_env_vars_included(self):
        svc = _mock_service(
            env=[
                {"key": "EMAIL", "default": "user@example.com"},
                {"key": "PASSWORD", "default": ""},
            ]
        )
        result = compose_generator._service_to_compose(svc)
        assert "EMAIL" in result["environment"]
        assert result["environment"]["EMAIL"] == "user@example.com"

    def test_env_override(self):
        svc = _mock_service(env=[{"key": "EMAIL", "default": "default@x.com"}])
        result = compose_generator._service_to_compose(svc, env_vars={"EMAIL": "custom@y.com"})
        assert result["environment"]["EMAIL"] == "custom@y.com"

    def test_hostname_substitution(self):
        svc = _mock_service(env=[{"key": "DEVICE_NAME", "default": "{hostname}"}])
        result = compose_generator._service_to_compose(svc, hostname="myhost")
        assert result["environment"]["DEVICE_NAME"] == "myhost"

    def test_ports_included(self):
        svc = _mock_service(ports=["28967:28967/tcp"])
        result = compose_generator._service_to_compose(svc)
        assert "28967:28967/tcp" in result["ports"]

    def test_volumes_included(self):
        svc = _mock_service(volumes=["/data/storj:/app/config"])
        result = compose_generator._service_to_compose(svc)
        assert "/data/storj:/app/config" in result["volumes"]

    def test_network_mode(self):
        svc = _mock_service(network_mode="host")
        result = compose_generator._service_to_compose(svc)
        assert result["network_mode"] == "host"

    def test_cap_add(self):
        svc = _mock_service(cap_add=["NET_ADMIN"])
        result = compose_generator._service_to_compose(svc)
        assert result["cap_add"] == ["NET_ADMIN"]

    def test_command(self):
        svc = _mock_service(command="/entrypoint.sh --arg")
        result = compose_generator._service_to_compose(svc)
        assert result["command"] == "/entrypoint.sh --arg"

    def test_required_env_placeholder(self):
        svc = _mock_service(env=[{"key": "TOKEN", "default": "", "required": True, "label": "API Token"}])
        result = compose_generator._service_to_compose(svc)
        assert result["environment"]["TOKEN"] == "<API Token>"

    def test_labels_included(self):
        svc = _mock_service()
        result = compose_generator._service_to_compose(svc)
        assert result["labels"]["cashpilot.managed"] == "true"
        assert result["labels"]["cashpilot.service"] == "honeygain"


class TestGenerateComposeSingle:
    def test_generates_valid_yaml(self):
        svc = _mock_service()
        with patch("app.compose_generator.get_service", return_value=svc):
            output = compose_generator.generate_compose_single("honeygain")
        assert "Generated by CashPilot" in output
        # Parse YAML (skip the comment header)
        lines = [line for line in output.split("\n") if not line.startswith("#")]
        parsed = yaml.safe_load("\n".join(lines))
        assert "services" in parsed

    def test_unknown_service_raises(self):
        with (
            patch("app.compose_generator.get_service", return_value=None),
            pytest.raises(ValueError, match="Unknown service"),
        ):
            compose_generator.generate_compose_single("nope")

    def test_no_image_raises(self):
        svc = {"name": "No Image", "slug": "noimg", "docker": {}}
        with (
            patch("app.compose_generator.get_service", return_value=svc),
            pytest.raises(ValueError, match="no Docker image"),
        ):
            compose_generator.generate_compose_single("noimg")


class TestGenerateComposeMulti:
    def test_generates_multi(self):
        svc1 = _mock_service("svc1", "Service 1")
        svc2 = _mock_service("svc2", "Service 2", image="img2:latest")

        def mock_get(slug):
            return {"svc1": svc1, "svc2": svc2}.get(slug)

        with patch("app.compose_generator.get_service", side_effect=mock_get):
            output = compose_generator.generate_compose_multi(["svc1", "svc2"])
        assert "cashpilot-svc1" in output
        assert "cashpilot-svc2" in output

    def test_empty_list_raises(self):
        with (
            patch("app.compose_generator.get_service", return_value=None),
            pytest.raises(ValueError, match="No deployable"),
        ):
            compose_generator.generate_compose_multi(["nonexistent"])


class TestGenerateComposeAll:
    def test_generates_all(self):
        svcs = [
            _mock_service("a", "A"),
            _mock_service("b", "B", image="b:latest"),
        ]
        with (
            patch("app.compose_generator.get_services", return_value=svcs),
            patch(
                "app.compose_generator.get_service",
                side_effect=lambda s: next((x for x in svcs if x["slug"] == s), None),
            ),
        ):
            output = compose_generator.generate_compose_all()
        assert "cashpilot-a" in output
        assert "cashpilot-b" in output


class TestEscapeInterpolation:
    def test_basic_escape(self):
        assert compose_generator._escape_interpolation("${FOO}") == "$${FOO}"

    def test_no_vars_unchanged(self):
        assert compose_generator._escape_interpolation("no-vars-here") == "no-vars-here"

    def test_already_escaped_not_doubled(self):
        assert compose_generator._escape_interpolation("$${ALREADY}") == "$${ALREADY}"

    def test_multiple_vars(self):
        result = compose_generator._escape_interpolation("${A} and ${B}")
        assert result == "$${A} and $${B}"

    def test_mixed_escaped_and_unescaped(self):
        result = compose_generator._escape_interpolation("$${OK} ${NEEDS_ESCAPE}")
        assert result == "$${OK} $${NEEDS_ESCAPE}"

    def test_empty_string(self):
        assert compose_generator._escape_interpolation("") == ""


class TestIsNamedVolume:
    def test_named_volume(self):
        assert compose_generator._is_named_volume("myvolume:/data") == "myvolume"

    def test_absolute_path(self):
        assert compose_generator._is_named_volume("/host/path:/data") is None

    def test_relative_path(self):
        assert compose_generator._is_named_volume("./relative:/data") is None

    def test_home_path(self):
        assert compose_generator._is_named_volume("~/home:/data") is None

    def test_empty_string(self):
        assert compose_generator._is_named_volume("") is None

    def test_no_colon(self):
        assert compose_generator._is_named_volume("myvolume") == "myvolume"


class TestNamedVolumeDeclaration:
    def test_named_volumes_declared_at_top_level(self):
        svc = _mock_service(volumes=["mydata:/app/data"])
        with patch("app.compose_generator.get_service", return_value=svc):
            output = compose_generator.generate_compose_single("honeygain")
        lines = [line for line in output.split("\n") if not line.startswith("#")]
        parsed = yaml.safe_load("\n".join(lines))
        assert "volumes" in parsed
        assert "mydata" in parsed["volumes"]

    def test_bind_mounts_no_top_level_volumes(self):
        svc = _mock_service(volumes=["/host/path:/container/path"])
        with patch("app.compose_generator.get_service", return_value=svc):
            output = compose_generator.generate_compose_single("honeygain")
        lines = [line for line in output.split("\n") if not line.startswith("#")]
        parsed = yaml.safe_load("\n".join(lines))
        assert "volumes" not in parsed or parsed.get("volumes") is None
