#!/usr/bin/env python3
"""Regenerate the guide navigation and index from the service catalog.

WHY THIS EXISTS
---------------
Two hand-maintained lists both drifted from ``services/*/*.yml``, and they
drifted in exactly the same way:

* ``mkdocs.yml`` listed 51 of the 52 guides, so ``proxybase-xyz.md`` was
  reachable only by URL — orphaned from the site's own navigation;
* ``docs/guides/README.md`` linked 49 services and said "**49 services**" while
  the catalog held 50 — missing the same one.

One service was added and two lists were not updated. That is not a mistake
anyone will stop making; it is a job for a generator. The catalog is already the
single source of truth for the UI, deployment, earnings collection and the
README tables, so the docs should read from it too.

WHAT IT WRITES
--------------
1. The ``Service Guides`` section of ``mkdocs.yml``'s nav, grouped by the
   catalog's current categories instead of one flat alphabetical list.
2. ``docs/guides/README.md`` — a filterable index table carrying the fields a
   visitor actually chooses on: category, what it needs (GPU / residential IP /
   storage), whether it runs in Docker or is app-only, payout minimum, status.

Run with ``--check`` in CI to fail when the two have drifted again.

WHAT IT MUST NOT DO
-------------------
Touch guide CONTENT. The guides are consistent and carry referral links, which
are revenue; this only rewrites the index and the nav.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app import provider_runtime  # noqa: E402

GUIDES = ROOT / "docs" / "guides"
MKDOCS = ROOT / "mkdocs.yml"
INDEX = GUIDES / "README.md"

#: Display order and headings. Deliberately not alphabetical: bandwidth is what
#: most visitors can actually run.
CATEGORY_TITLES = [
    ("bandwidth", "Bandwidth Sharing"),
    ("depin", "DePIN"),
]

#: Guides under docs/guides/ that are not service guides and must be left alone.
NON_SERVICE_GUIDES = {"README", "prometheus-metrics"}


def runtime_disabled_slugs() -> frozenset[str]:
    """Read deployment policy from the same truth matrix as the API and UI."""
    return frozenset(slug for slug, provider in provider_runtime.PROVIDERS.items() if not provider.deployment_allowed)


def runtime_restricted_slugs() -> frozenset[str]:
    """Providers whose dedicated platform lane must not look like generic Docker."""
    return frozenset(
        slug
        for slug, provider in provider_runtime.PROVIDERS.items()
        if provider.deployment_policy == "platform_restricted"
    )


def load_services() -> list[dict]:
    """Every catalog entry, sorted by display name within its category."""
    services = []
    for path in sorted((ROOT / "services").glob("*/*.yml")):
        if path.name.startswith("_"):
            continue
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        slug = data.get("slug") or path.stem
        services.append(
            {
                "slug": slug,
                "name": data.get("name") or slug,
                "category": data.get("category") or path.parent.name,
                "short": (data.get("short_description") or data.get("description") or "").strip(),
                "status": (data.get("status") or "").strip(),
                "requirements": data.get("requirements") or {},
                "payment": data.get("payment") or {},
                "dockerised": bool((data.get("docker") or {}).get("image", "").strip()),
            }
        )
    return sorted(services, key=lambda s: s["name"].lower())


def by_category(services: list[dict]) -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = {}
    for svc in services:
        grouped.setdefault(svc["category"], []).append(svc)
    return grouped


def needs(svc: dict) -> str:
    """What the machine must have, in the words a reader is choosing on."""
    req = svc["requirements"]
    bits = []
    if req.get("gpu"):
        bits.append("GPU")
    if req.get("residential_ip"):
        bits.append("Residential IP")
    if str(req.get("min_storage") or "").strip():
        bits.append(f"Storage {req['min_storage']}")
    if str(req.get("min_bandwidth") or "").strip():
        bits.append(str(req["min_bandwidth"]))
    # An empty cell reads as "nothing special", which is the honest answer here:
    # every field above is absent, and absent means the catalog declares no
    # requirement rather than that one exists and is unknown.
    return ", ".join(bits) or "—"


def render_index(services: list[dict]) -> str:
    grouped = by_category(services)
    disabled_slugs = runtime_disabled_slugs()
    restricted_slugs = runtime_restricted_slugs()
    out = [
        "<!-- GENERATED by scripts/sync_docs_nav.py from services/*/*.yml. Do not edit by hand. -->",
        "",
        "# Service guides",
        "",
    ]
    if "earnapp" in restricted_slugs:
        out += [
            "> EarnApp runtime is platform-restricted: official Linux x64 uses the dedicated",
            "> Ubuntu LXD lane; MacOS/iOS emulation and generic Docker deploy remain disabled.",
            "",
        ]
    out += [
        "Setup and configuration for every service CashPilot supports.",
        "",
        f"**{len(services)} providers** across {len(grouped)} categories. "
        "The table is sortable — click a heading to reorder it.",
        "",
        '!!! tip "Choosing what to run"',
        "",
        "    **Bandwidth** services want a residential IP and pay the least per",
        "    machine. **DePIN** providers usually need account/session or",
        "    browser-profile setup before unattended runtime is reliable.",
        "",
    ]
    for key, title in CATEGORY_TITLES:
        items = grouped.get(key)
        if not items:
            continue
        out += [
            f"## {title}",
            "",
            "| Service | Needs | Runs as | Minimum payout | Status |",
            "|---|---|---|---|---|",
        ]
        for svc in items:
            payout = str(svc["payment"].get("minimum_payout") or "—").strip() or "—"
            if str(svc["slug"]) in disabled_slugs:
                runs = "Collector only"
                status = "runtime disabled"
            elif str(svc["slug"]) in restricted_slugs:
                runs = "Ubuntu LXD"
                status = "platform restricted"
            else:
                runs = "Docker" if svc["dockerised"] else "App only"
                status = svc["status"] or "—"
            out.append(f"| [{svc['name']}]({svc['slug']}.md) | {needs(svc)} | {runs} | {payout} | {status} |")
        out.append("")
    # Linked from the index prose, but deliberately not added to the nav above:
    # it has its own top-level entry there.
    out += [
        "## Not a service guide",
        "",
        "- [Prometheus metrics](prometheus-metrics.md) — what CashPilot exports for scraping.",
        "",
    ]
    return "\n".join(out)


def render_nav(services: list[dict]) -> str:
    """The nav block, grouped by category and indented for mkdocs.yml."""
    grouped = by_category(services)
    lines = ["  - Service Guides:", "    - Overview: guides/README.md"]
    for key, title in CATEGORY_TITLES:
        items = grouped.get(key)
        if not items:
            continue
        lines.append(f"    - {title}:")
        lines += [f"      - {svc['name']}: guides/{svc['slug']}.md" for svc in items]
    # prometheus-metrics.md is NOT added here: it already has a top-level nav
    # entry, and it is a reference page rather than a service guide. Listing it
    # in both places put the same page in the nav twice -- caught by counting
    # refs after the first generated run, not by reading the output.
    return "\n".join(lines)


def splice_nav(mkdocs_text: str, nav_block: str) -> str:
    """Replace the existing Service Guides section, leaving the rest untouched."""
    pattern = re.compile(r"^  - Service Guides:\n(?:^ {4,}.*\n?)*", re.M)
    if not pattern.search(mkdocs_text):
        raise SystemExit("mkdocs.yml has no '  - Service Guides:' section to replace")
    return pattern.sub(nav_block + "\n", mkdocs_text, count=1)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit non-zero if anything is out of date")
    args = parser.parse_args()

    services = load_services()
    if not services:
        raise SystemExit("no services found; refusing to write an empty nav")

    # Guard against silently dropping a guide that has no catalog entry.
    on_disk = {p.stem for p in GUIDES.glob("*.md")} - NON_SERVICE_GUIDES
    unknown = on_disk - {s["slug"] for s in services}
    if unknown:
        raise SystemExit(f"guides with no catalog entry, so they cannot be placed: {sorted(unknown)}")

    new_index = render_index(services)
    new_mkdocs = splice_nav(MKDOCS.read_text(encoding="utf-8"), render_nav(services))

    stale = []
    if INDEX.read_text(encoding="utf-8") != new_index:
        stale.append(str(INDEX.relative_to(ROOT)))
    if MKDOCS.read_text(encoding="utf-8") != new_mkdocs:
        stale.append(str(MKDOCS.relative_to(ROOT)))

    if args.check:
        if stale:
            print("Out of date with the catalog: " + ", ".join(stale))
            print("Run: python scripts/sync_docs_nav.py")
            return 1
        print(f"Up to date: {len(services)} services.")
        return 0

    INDEX.write_text(new_index, encoding="utf-8")
    MKDOCS.write_text(new_mkdocs, encoding="utf-8")
    print(f"Wrote nav and index for {len(services)} services." if stale else "Already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
